[package]
name = "yamadesk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
microdotphat = "0.2.5"
reqwest = { version = "0.12.28", features = ["json"] }
rppal = { version = "0.22.1", features = ["hal"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
toml = "0.9.12"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
